version: "3"

networks:
  proxylampy:
    external: true
  serverlampy:
    external: true
  net:
    driver: overlay
    attachable: true
services:
  riot:
    image: vectorim/element-web:v1.7.25
    volumes:
      - ${PWD}/riot/config.json:/app/config.json:ro
    networks:
      - serverlampy
      - proxylampy
      - net
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.riot.rule=Host(`riot.traefik.me`)"
        - "traefik.http.routers.riot-tls.tls.domains[0].main=riot.traefik.me"
        - "traefik.http.routers.riot.tls=true"
        - "traefik.http.services.riot.loadbalancer.server.port=80"
  matrix:
    image: nginx:1.19.10
    volumes:
      - ${PWD}/nginx/matrix.conf:/etc/nginx/conf.d/matrix.conf
      - ${PWD}/nginx/www:/var/www/
    networks:
      - serverlampy
      - proxylampy
      - net
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.matrix.rule=Host(`matrix.traefik.me`)"
        - "traefik.http.routers.matrix-tls.tls.domains[0].main=matrix.traefik.me"
        - "traefik.http.routers.matrix.tls=true"
        - "traefik.http.services.matrix.loadbalancer.server.port=80"
  synapse:
    image: matrixdotorg/synapse:v1.31.0
    networks:
      - serverlampy
      - proxylampy
      - net
    environment:
      SYNAPSE_CONFIG_DIR: "/data"
      SYNAPSE_CONFIG_PATH: "/data/homeserver.yaml"
      UID: "1000"
      GID: "1000"
      TZ: "Europe/Paris"
    volumes:
      - ${PWD}/synapse:/data
      - ${PWD}/synapse/whatsapp:/mautrix-whatsapp
      - ${PWD}/synapse/signal:/mautrix-signal
      - ${PWD}/synapse/appservice-irc:/matrix-appservice-irc
    depends_on:
      - postgresql
      - redis
      - smtp
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.synapse.rule=Host(`synapse.traefik.me`)"
        - "traefik.http.routers.synapse-tls.tls.domains[0].main=synapse.traefik.me"
        - "traefik.http.routers.synapse.tls=true"
        - "traefik.http.services.synapse.loadbalancer.server.port=8008"